### ISSUE TITLE
Error al mostrar logos en html

### ISSUE THREAD

**Issue by OsmanH25** [CodeSystem2022/Project-Primates-Python#1]
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" type="text/css" href="../static/main.css"/>
    <link rel="shortcut icon" href="../static/assets/logotipo.png">

</head>
<body class="image-background">
        <nav class="navBar">
                <img
                    src="../static/assets/IsoLogotipo.png"
                    alt=""
                >
            </nav>
            <div class="decorativeBarTop">

**Comment by NicoSgandurra** [comment]
Fixed
